### ISSUE TITLE
[feature] Add configuration handler, with environments overwrites

### ISSUE THREAD

**Issue by joni7777** [joni7777/netcore-seed#2]
Need to implement config service, that loads the configuration from the config dir and overwrite the configuration by environments

config\
 - default.json
 - development.json
 - production.json
 - development.local.json

with c# env development the configs will be read by the following order:
default.json -> development.json -> development.local.json
creating unioned configuration

**Comment by Meir017** [comment]
maybe something like this:
```cs
public void ConfigureServices(IServiceCollection services, IHostingEnvironment environment)
{
    var config = new ConfigurationBuilder()
        .AddJsonFile("./config/default.json", optional: false, reloadOnChange: true)
        .AddJsonFile("./config/development.json", optional: true, reloadOnChange: true)
        .AddJsonFile("./config/development.local.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"./config/{environment.EnvironmentName}.json", optional: false, reloadOnChange: true);
}
```
