### ISSUE TITLE
[feature] add system - health-checks

### ISSUE THREAD

**Issue by joni7777** [joni7777/netcore-seed#5]
Add health-checks as dll to the service

**Comment by Meir017** [comment]
for reference:
* official Microsoft health-checks: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health
* community - https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks

**Comment by joni7777** [comment]
merged
